### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Domosed-gamin** [MichaelDipperstein/tankvufo#1]
Hi. I have error of compilation. 

ringo@qwerty:~/Загрузки/tankvufo-master$ make
gcc -Wall -Wextra `ncursesw6-config --cflags` -c tankvufo.c -o tankvufo.o
/bin/sh: 1: ncursesw6-config: not found
tankvufo.c:43:14: error: unknown type name ‘cchar_t’
 static const cchar_t GROUND_CHAR = {WA_NORMAL, L"▔", 0};
              ^~~~~~~
tankvufo.c:43:48: warning: excess elements in scalar initializer
 static const cchar_t GROUND_CHAR = {WA_NORMAL, L"▔", 0};
                                                ^~~~~~
tankvufo.c:43:48: note: (near initialization for ‘GROUND_CHAR’)
tankvufo.c:43:56: warning: excess elements in scalar initializer
 static const cchar_t GROUND_CHAR = {WA_NORMAL, L"▔", 0};
                                                        ^
tankvufo.c:43:56: note: (near initialization for ‘GROUND_CHAR’)
tankvufo.c:44:14: error: unknown type name ‘cchar_t’
 static const cchar_t UFO_SHOT_CHAR = {WA_NORMAL, L"●", 0};
              ^~~~~~~
tankvufo.c:44:50: warning: excess elements in scalar initializer
 static const cchar_t UFO_SHOT_CHAR = {WA_NORMAL, L"●", 0};
                                                  ^~~~~~
tankvufo.c:44:50: note: (near initialization for ‘UFO_SHOT_CHAR’)
tankvufo.c:44:58: warning: excess elements in scalar initializer
 static const cchar_t UFO_SHOT_CHAR = {WA_NORMAL, L"●", 0};
                                                          ^
tankvufo.c:44:58: note: (near initialization for ‘UFO_SHOT_CHAR’)
tankvufo.c:45:14: error: unknown type name ‘cchar_t’
 static const cchar_t TANK_SHOT_CHAR = {WA_NORMAL, L"▪", 0};
              ^~~~~~~
tankvufo.c:45:51: warning: excess elements in scalar initializer
 static const cchar_t TANK_SHOT_CHAR = {WA_NORMAL, L"▪", 0};
                                                   ^~~~~~
tankvufo.c:45:51: note: (near initialization for ‘TANK_SHOT_CHAR’)
tankvufo.c:45:59: warning: excess elements in scalar initializer
 static const cchar_t TANK_SHOT_CHAR = {WA_NORMAL, L"▪", 0};
                                                           ^
tankvufo.c:45:59: note: (near initialization for ‘TANK_SHOT_CHAR’)
tankvufo.c:46:14: error: unknown type name ‘cchar_t’
 static const cchar_t BOX_CHAR = {WA_NORMAL, L"█", 0};
              ^~~~~~~
tankvufo.c:46:45: warning: excess elements in scalar initializer
 static const cchar_t BOX_CHAR = {WA_NORMAL, L"█", 0};
                                             ^~~~~~
tankvufo.c:46:45: note: (near initialization for ‘BOX_CHAR’)
tankvufo.c:46:53: warning: excess elements in scalar initializer
 static const cchar_t BOX_CHAR = {WA_NORMAL, L"█", 0};
                                                     ^
tankvufo.c:46:53: note: (near initialization for ‘BOX_CHAR’)
tankvufo.c:56:35: error: initializer element is not constant
 static const int TANK_TREAD_ROW = V20_ROWS - 2;
                                   ^~~~~~~~
tankvufo.c:57:36: error: initializer element is not constant
 static const int TANK_TURRET_ROW = TANK_TREAD_ROW - 1;
                                    ^~~~~~~~~~~~~~
tankvufo.c:58:33: error: initializer element is not constant
 static const int TANK_GUN_ROW = TANK_TURRET_ROW - 1;
                                 ^~~~~~~~~~~~~~~
tankvufo.c:59:40: error: initializer element is not constant
 static const int TANK_SHOT_START_ROW = TANK_GUN_ROW - 1;
                                        ^~~~~~~~~~~~
tankvufo.c:62:31: error: initializer element is not constant
 static const int UFO_BOTTOM = TANK_SHOT_START_ROW - 2;
                               ^~~~~~~~~~~~~~~~~~~
tankvufo.c:63:28: error: initializer element is not constant
 static const int UFO_TOP = SCORE_ROW + 2;
                            ^~~~~~~~~
tankvufo.c: In function ‘main’:
tankvufo.c:161:5: warning: implicit declaration of function ‘mvwhline_set’ [-Wimplicit-function-declaration]
     mvwhline_set(v20_win, V20_ROWS - 1, 0, &GROUND_CHAR, V20_COLS);
     ^~~~~~~~~~~~
tankvufo.c: In function ‘move_tank_shot’:
tankvufo.c:635:9: error: unknown type name ‘cchar_t’
         cchar_t c;
         ^~~~~~~
tankvufo.c:636:9: warning: implicit declaration of function ‘mvwin_wch’ [-Wimplicit-function-declaration]
         mvwin_wch(win, tank->shot_y, tank->shot_x, &c);
         ^~~~~~~~~
tankvufo.c:638:27: error: request for member ‘chars’ in something not a structure or union
         if (TANK_SHOT_CHAR.chars[0] == c.chars[0])
                           ^
tankvufo.c:638:41: error: request for member ‘chars’ in something not a structure or union
         if (TANK_SHOT_CHAR.chars[0] == c.chars[0])
                                         ^
tankvufo.c:654:13: warning: implicit declaration of function ‘mvwadd_wch’ [-Wimplicit-function-declaration]
             mvwadd_wch(win, tank->shot_y, tank->shot_x, &TANK_SHOT_CHAR);
             ^~~~~~~~~~
tankvufo.c: In function ‘check_tank_shot’:
tankvufo.c:726:9: error: unknown type name ‘cchar_t’
         cchar_t c;
         ^~~~~~~
tankvufo.c:731:26: error: request for member ‘chars’ in something not a structure or union
         if (UFO_SHOT_CHAR.chars[0] == c.chars[0])
                          ^
tankvufo.c:731:40: error: request for member ‘chars’ in something not a structure or union
         if (UFO_SHOT_CHAR.chars[0] == c.chars[0])
                                        ^
tankvufo.c: In function ‘move_ufo_shot’:
tankvufo.c:801:5: error: unknown type name ‘cchar_t’
     cchar_t c;
     ^~~~~~~
tankvufo.c:806:22: error: request for member ‘chars’ in something not a structure or union
     if (UFO_SHOT_CHAR.chars[0] == c.chars[0])
                      ^
tankvufo.c:806:36: error: request for member ‘chars’ in something not a structure or union
     if (UFO_SHOT_CHAR.chars[0] == c.chars[0])
                                    ^
Makefile:15: ошибка выполнения рецепта для цели «tankvufo.o»
make: *** [tankvufo.o] Ошибка 1

**Comment by MichaelDipperstein** [comment]
Sorry about the late response.  I just notice your issue.  I never check the issues.

make can't find ncursesw6-config, which probably means that the development package for ncursesw is not installed.  If you think it is, you might want to try the latest code.  You'll need PortAudio, because I added sound, but it doesn't use ncursesw6-config to compile.

If you have any other issues, email me directly.  I check my email fairly regularly.

-Michael

**Comment by MichaelDipperstein** [comment]
I'm closing this because OP hasn't responded and build instructions are much clearer now.
